#!/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7

import numpy

def nonlin(x,deriv=False):
	if(deriv==True):
		return x*(1-x)

	return 1/(1+numpy.exp(-x))
z=12.0
zz=6.0
n=0.976
o=0.024
X = numpy.array([[0,0],[0,1],[1,0],[1,1]]) 
#y = numpy.array([[1],[0],[0],[0]])
numpy.random.seed(3)
for k in range(30000000000):
# randomly initialize our weights with mean 0
 syn0 = z*numpy.random.random((2,3)) - zz
 syn1 = z*numpy.random.random((3,1)) - zz
# Feed forward through layers 0, 1, and 2
 l0 = X
 l1 = nonlin(numpy.dot(l0,syn0))
 l2 = nonlin(numpy.dot(l1,syn1))

# if (l2[0]<=o) and (l2[1]<=o) and (l2[2]<=o) and (l2[3]<=o):
#  f = open("R9FALSE__l2c", "a")
#  g = open("R9FALSE__syn0c", "a")
#  h = open("R9FALSE__syn1c", "a")   
#  print(l2.T, file=f)
#  print(syn0, file=g)
#  print(syn1.T, file=h)
#  f.close() 
#  g.close()
#  h.close()
 if (l2[0]<=o) and (l2[1]<=o) and (l2[2]<=o) and (l2[3]>=n):
  f = open("R9AND__l2c", "a")
  g = open("R9AND__syn0c", "a")
  h = open("R9AND__syn1c", "a")   
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
 if (l2[0]<=o) and (l2[1]<=o) and (l2[2]>=n) and (l2[3]<o):
  f = open("R9PMINUSQ__l2c", "a")
  g = open("R9PMINUSQ__syn0c", "a")
  h = open("R9PMINUSQ__syn1c", "a")   
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
 if (l2[0]<=o) and (l2[1]<=o) and (l2[2]>=n) and (l2[3]>=n):
  f = open("R9P__l2c", "a")
  g = open("R9P__syn0c", "a")
  h = open("R9P__syn1c", "a")   
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
 if (l2[0]<=o) and (l2[1]>=n) and (l2[2]<=o) and (l2[3]<=o):
  f = open("R9QminusP__l2c", "a")
  g = open("R9QminusP__syn0c", "a")
  h = open("R9QminusP__syn1c", "a")
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
 if (l2[0]<=o) and (l2[1]>=n) and (l2[2]<=o) and (l2[3]>=n):
  f = open("R9Q__l2c", "a")
  g = open("R9Q__syn0c", "a")
  h = open("R9Q__syn1c", "a")   
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
 if (l2[0]<=o) and (l2[1]>=n) and (l2[2]>=n) and (l2[3]<=o):
  f = open("R9XOR__l2c", "a")
  g = open("R9XOR__syn0c", "a")
  h = open("R9XOR__syn1c", "a")   
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
 if (l2[0]<=o) and (l2[1]>=n) and (l2[2]>=n) and (l2[3]>=n):
  f = open("R9OR__l2c", "a")
  g = open("R9OR__syn0c", "a")
  h = open("R9OR__syn1c", "a")   
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
 if (l2[0]>=n) and (l2[1]<=o) and (l2[2]<=o) and (l2[3]<=o):
  f = open("R9NAND__l2c", "a")
  g = open("R9NAND__syn0c", "a")
  h = open("R9NAND__syn1c", "a")   
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
 if (l2[0]>=n) and (l2[1]<=o) and (l2[2]<=o) and (l2[3]>=n):
  f = open("R9IFF__l2c", "a")
  g = open("R9IFF__syn0c", "a")
  h = open("R9IFF__syn1c", "a")   
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
 if (l2[0]>=n) and (l2[1]<=o) and (l2[2]>=n) and (l2[3]<=o):
  f = open("R9NOTQ__l2c", "a")
  g = open("R9NOTQ__syn0c", "a")
  h = open("R9NOTQ__syn1c", "a")   
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
 if (l2[0]>=n) and (l2[1]<=o) and (l2[2]>=n) and (l2[3]>=n):
  f = open("R9IMPLICATION__l2c", "a")
  g = open("R9IMPLICATION__syn0c", "a")
  h = open("R9IMPLICATION__syn1c", "a")   
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
 if (l2[0]>=n) and (l2[1]>=n) and (l2[2]<=o) and (l2[3]<=o):
  f = open("R9NOTP__l2c", "a")
  g = open("R9NOTP__syn0c", "a")
  h = open("R9NOTP__syn1c", "a")   
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
 if (l2[0]>=n) and (l2[1]>=n) and (l2[2]<=o) and (l2[3]>=n):
  f = open("R9REVIMPLICATION__l2c", "a")
  g = open("R9REVIMPLICATION__syn0c", "a")
  h = open("R9REVIMPLICATION__syn1c", "a")
  print(l2.T, file=f)
  print(syn0, file=g)
  print(syn1.T, file=h)
  f.close() 
  g.close()
  h.close()
# if (l2[0]>=n) and (l2[1]>=n) and (l2[2]>=n) and (l2[3]>=n):
#  f = open("R9TRUE__l2c", "a")
#  g = open("R9TRUE__syn0c", "a")
#  h = open("R9TRUE__syn1c", "a")   
#  print(l2.T, file=f)
#  print(syn0, file=g)
#  print(syn1.T, file=h)
#  f.close() 
#  g.close()
#  h.close()
